In [44]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [45]:
import os 
os.chdir("C:/Users/arman/ostad_code")

In [46]:
df=pd.read_csv("Breast_Cancer_Diagnostic.csv")
df

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,diagnosis
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,M
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,M
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,M
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,M
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,M
...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,M
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,M
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,M
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,M
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,B

In [47]:
df.isna().sum()

radius_mean               0
texture_mean              0
perimeter_mean            0
area_mean                 0
smoothness_mean           0
compactness_mean          0
concavity_mean            0
concave points_mean       0
symmetry_mean             0
fractal_dimension_mean    0
diagnosis                 0
dtype: int64

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   radius_mean             569 non-null    float64
 1   texture_mean            569 non-null    float64
 2   perimeter_mean          569 non-null    float64
 3   area_mean               569 non-null    float64
 4   smoothness_mean         569 non-null    float64
 5   compactness_mean        569 non-null    float64
 6   concavity_mean          569 non-null    float64
 7   concave points_mean     569 non-null    float64
 8   symmetry_mean           569 non-null    float64
 9   fractal_dimension_mean  569 non-null    float64
 10  diagnosis               569 non-null    object
dtypes: float64(10), object(1)
memory usage: 49.0+ KB

# svm ki

# svm holo ata 2ta datar modde amn akta maximum gab barkore ba line tanbe jekan theke 2ta datar durutto sob theke basi hoi

In [49]:
x=df.drop("diagnosis",axis=1)
y=df["diagnosis"]

In [50]:
x

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883
...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884

In [51]:
y

0      M
1      M
2      M
3      M
4      M
      ..
564    M
565    M
566    M
567    M
568    B
Name: diagnosis, Length: 569, dtype: object

In [52]:
from sklearn.preprocessing import MinMaxScaler
mms=MinMaxScaler()
x_scaler=mms.fit_transform(x)
x_scaler

array([[0.52103744, 0.0226581 , 0.54598853, ..., 0.73111332, 0.68636364,
        0.60551811],
       [0.64314449, 0.27257355, 0.61578329, ..., 0.34875746, 0.37979798,
        0.14132266],
       [0.60149557, 0.3902604 , 0.59574321, ..., 0.63568588, 0.50959596,
        0.21124684],
       ...,
       [0.45525108, 0.62123774, 0.44578813, ..., 0.26351889, 0.26767677,
        0.13732098],
       [0.64456434, 0.66351031, 0.66553797, ..., 0.7554672 , 0.67525253,
        0.42544229],
       [0.03686876, 0.50152181, 0.02853984, ..., 0.        , 0.26616162,
        0.18702612]])

In [53]:
x=pd.DataFrame(data=x_scaler)
x

,0,1,2,3,4,5,6,7,8,9
0,0.521037,0.022658,0.545989,0.363733,0.593753,0.792037,0.703140,0.731113,0.686364,0.605518
1,0.643144,0.272574,0.615783,0.501591,0.289880,0.181768,0.203608,0.348757,0.379798,0.141323
2,0.601496,0.390260,0.595743,0.449417,0.514309,0.431017,0.462512,0.635686,0.509596,0.211247
3,0.210090,0.360839,0.233501,0.102906,0.811321,0.811361,0.565604,0.522863,0.776263,1.000000
4,0.629893,0.156578,0.630986,0.489290,0.430351,0.347893,0.463918,0.518390,0.378283,0.186816
...,...,...,...,...,...,...,...,...,...,...
564,0.690000,0.428813,0.678668,0.566490,0.526948,0.296055,0.571462,0.690358,0.336364,0.132056
565,0.622320,0.626987,0.604036,0.474019,0.407782,0.257714,0.337395,0.486630,0.349495,0.113100
566,0.455251,0.621238,0.445788,0.303118,0.288165,0.254340,0.216753,0.263519,0.267677,0.137321
567,0.644564,0.663510,0.665538,0.475716,0.588336,0.790197,0.823336,0.755467,0.675253,0.425442
568,0.036869,0.501522,0.028540,0.015907,0.000000,0.074351,0.000000,0.000000,0.266162,0.187026

In [54]:
x.shape

(569, 10)

In [55]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=41)

In [56]:
x_train

,0,1,2,3,4,5,6,7,8,9
475,0.276823,0.203585,0.270196,0.154146,0.340977,0.194191,0.136715,0.152982,0.325758,0.193134
298,0.344503,0.286101,0.327759,0.207678,0.118534,0.100669,0.057990,0.068290,0.290404,0.124263
220,0.315633,0.116672,0.304678,0.180445,0.395685,0.207748,0.091097,0.127386,0.151515,0.283909
549,0.181693,0.490362,0.173450,0.092513,0.264422,0.143059,0.036270,0.040557,0.462626,0.280539
567,0.644564,0.663510,0.665538,0.475716,0.588336,0.790197,0.823336,0.755467,0.675253,0.425442
...,...,...,...,...,...,...,...,...,...,...
469,0.219556,0.286439,0.225209,0.112534,0.585628,0.395436,0.238988,0.276541,0.453030,0.475779
407,0.277770,0.394319,0.268399,0.157370,0.206554,0.195632,0.143533,0.092793,0.262626,0.235468
243,0.320365,0.475482,0.309239,0.189396,0.250970,0.149347,0.110052,0.116501,0.360101,0.091196
321,0.623740,0.336490,0.603345,0.479533,0.248894,0.203239,0.270619,0.383996,0.438384,0.021061
80,0.211510,0.380791,0.207449,0.109438,0.519726,0.227716,0.107568,0.110984,0.394949,0.423126

In [57]:
y_train

475    B
298    B
220    B
549    B
567    M
      ..
469    B
407    B
243    B
321    M
80     B
Name: diagnosis, Length: 455, dtype: object

In [58]:
x_test

,0,1,2,3,4,5,6,7,8,9
285,0.264991,0.293879,0.249050,0.146554,0.282567,0.069873,0.004358,0.014533,0.321717,0.180918
347,0.368167,0.170105,0.352982,0.222778,0.326081,0.179191,0.107966,0.175348,0.232828,0.192923
89,0.362488,0.187014,0.359201,0.215652,0.546809,0.351267,0.233505,0.351093,0.533333,0.284330
496,0.268304,0.286101,0.268813,0.145111,0.496253,0.349733,0.187840,0.252187,0.293434,0.391323
319,0.257892,0.246534,0.240550,0.141591,0.207096,0.046500,0.031443,0.084443,0.208081,0.118997
...,...,...,...,...,...,...,...,...,...,...
325,0.269251,0.256679,0.258863,0.146935,0.452920,0.175633,0.074813,0.104722,0.326768,0.208088
504,0.108240,0.106865,0.122314,0.044624,1.000000,0.627323,0.227976,0.261034,0.665657,0.949031
396,0.309007,0.310450,0.306199,0.175864,0.480906,0.292375,0.201031,0.267445,0.376768,0.228096
507,0.193052,0.250592,0.189759,0.094592,0.602781,0.269063,0.095197,0.212127,0.451515,0.627633
357,0.326045,0.219817,0.309101,0.190965,0.314164,0.109012,0.035192,0.103777,0.183838,0.186816

In [59]:
y_test

285    B
347    B
89     B
496    B
319    B
      ..
325    B
504    B
396    B
507    B
357    B
Name: diagnosis, Length: 114, dtype: object

# akn amra model implement korbo

In [60]:
from sklearn.svm import SVC
svm_model=SVC() #akane default kernel nese ,,extra kno perameter dewa hoinai svc ar modde tai.
#default:kernel="rbf",c=1,gamma="scale"
#ata dewar asol karon holo model kon pertation a kaj korbe,,maje akta dak deye naki onk gula class ar maj deye dag deye etc
svm_model.fit(x_train,y_train)

SVC()

# svm=support vector machine
# svc=support vector classification

In [61]:
svm_model.score(x_test,y_test)

0.9824561403508771

# akn amra different kernel deye accuracy dakhbo

In [62]:
#kernel sadaronto 5 doroner hoye thake jrmon kernel=linear,poly,rbf,sigmoid ,precomputed,,
###ar C ar mane holo model koto ta strict ba kothor hobe,,c ar man basidele model basi strict hobe ,,c ar man komdele model kom strict hbe,kom vul dorbe

In [65]:
from sklearn.svm import SVC
model=SVC(kernel="linear", C=20,gamma="auto") #gamma auto dete hoi nijera select korar somoi
model.fit(x_train,y_train)

SVC(C=20, gamma='auto', kernel='linear')

In [66]:
model.score(x_test,y_test)

0.956140350877193

# tahole buja gelo amader nijer dewar theke uporer default parameter a best accuracy passe

In [67]:
###but amra kevabe bujbo onno model a.j kon perameter a best accuracy pabe,,ar aro system ase.jake greed search cv bola hoi.

# amra new page a GridSearchcCV library deye kaj korbo